---
parameters:
    ez_phar: 'https://ezsystems.github.io/launchpad/ez.phar'
    ez_phar_version: 'https://ezsystems.github.io/launchpad/ez.phar.version'

services:

    ezlaunchpad_update.listener:
        class: eZ\Launchpad\Listener\ApplicationUpdate
        arguments:
            - {env: "%app_env%", dir: "%app_dir%", url: "%ez_phar%", version: "%ez_phar_version%"}
            - "@project_configuration"
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    ezlaunchpad_d4m.listener:
        class: eZ\Launchpad\Listener\D4MListener
        arguments:
            - {env: "%app_env%"}
            - "@project_configuration"
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    ezlaunchpad_command_exception.listener:
        class: eZ\Launchpad\Listener\CommandException
        tags:
            - { name: kernel.event_listener, event: console.error, method: onExceptionAction }

    ezlaunchpad_command_start.listener:
        class: eZ\Launchpad\Listener\CommandStart
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }


    ezlaunchpad_command_terminate.listener:
        class: eZ\Launchpad\Listener\CommandTerminate
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminateAction }
